"""Add workflow tables

Revision ID: 01bafa292c77
Revises: 237f241709ac
Create Date: 2025-09-29 18:31:43.124372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01bafa292c77'
down_revision: Union[str, None] = '237f241709ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_table('document_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_history_id'), 'document_history', ['id'], unique=False)
    op.create_table('document_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', 'SUPERSEDED', name='documentstatus'), nullable=True),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_steps.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_workflows_id'), 'document_workflows', ['id'], unique=False)
    op.create_table('document_workflow_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DELEGATED', name='approvalstatus'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['document_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_workflow_approvals_id'), 'document_workflow_approvals', ['id'], unique=False)
    
    # Сначала удаляем внешние ключи
    op.drop_constraint('workflow_steps_workflow_id_fkey', 'workflow_steps', type_='foreignkey')
    op.drop_constraint('workflow_steps_assigned_to_fkey', 'workflow_steps', type_='foreignkey')
    
    # Теперь удаляем таблицы
    op.drop_index('ix_workflow_step_logs_id', table_name='workflow_step_logs')
    op.drop_table('workflow_step_logs')
    op.drop_index('ix_workflow_instances_id', table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index('ix_workflows_id', table_name='workflows')
    op.drop_table('workflows')
    
    # Обновляем workflow_steps
    op.add_column('workflow_steps', sa.Column('template_id', sa.Integer(), nullable=False))
    op.add_column('workflow_steps', sa.Column('approver_role', sa.String(length=100), nullable=True))
    op.add_column('workflow_steps', sa.Column('approver_user_id', sa.Integer(), nullable=True))
    op.add_column('workflow_steps', sa.Column('escalation_hours', sa.Integer(), nullable=True))
    op.alter_column('workflow_steps', 'step_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'workflow_steps', 'users', ['approver_user_id'], ['id'])
    op.create_foreign_key(None, 'workflow_steps', 'workflow_templates', ['template_id'], ['id'])
    op.drop_column('workflow_steps', 'workflow_id')
    op.drop_column('workflow_steps', 'assigned_to')
    op.drop_column('workflow_steps', 'step_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('step_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('workflow_steps', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workflow_steps', sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.create_foreign_key('workflow_steps_assigned_to_fkey', 'workflow_steps', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key('workflow_steps_workflow_id_fkey', 'workflow_steps', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workflow_steps', 'step_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('workflow_steps', 'escalation_hours')
    op.drop_column('workflow_steps', 'approver_user_id')
    op.drop_column('workflow_steps', 'approver_role')
    op.drop_column('workflow_steps', 'template_id')
    op.create_table('workflows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='workflows_created_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='workflows_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_workflows_id', 'workflows', ['id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_instances_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('started_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_step'], ['workflow_steps.id'], name='workflow_instances_current_step_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='workflow_instances_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name='workflow_instances_started_by_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_instances_workflow_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_instances_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_workflow_instances_id', 'workflow_instances', ['id'], unique=False)
    op.create_table('workflow_step_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_instance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name='workflow_step_logs_performed_by_fkey'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], name='workflow_step_logs_step_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name='workflow_step_logs_workflow_instance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_step_logs_pkey')
    )
    op.create_index('ix_workflow_step_logs_id', 'workflow_step_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_document_workflow_approvals_id'), table_name='document_workflow_approvals')
    op.drop_table('document_workflow_approvals')
    op.drop_index(op.f('ix_document_workflows_id'), table_name='document_workflows')
    op.drop_table('document_workflows')
    op.drop_index(op.f('ix_document_history_id'), table_name='document_history')
    op.drop_table('document_history')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
