"""Remove version and uploaded_by from documents table

Revision ID: 073bc109bb7a
Revises: 34db57af916b
Create Date: 2025-09-30 15:31:32.024480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073bc109bb7a'
down_revision: Union[str, None] = '34db57af916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_uploaded_by_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=True))
    op.create_foreign_key('documents_uploaded_by_fkey', 'documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###
