"""Add workflow_statuses table and workflow_status_id to document_revisions

Revision ID: 07b1d37e9b40
Revises: a07d98eda1ef
Create Date: 2025-10-12 13:32:21.978758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b1d37e9b40'
down_revision: Union[str, None] = 'a07d98eda1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('name_native', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_statuses_id'), 'workflow_statuses', ['id'], unique=False)
    op.add_column('document_revisions', sa.Column('workflow_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_revisions', 'workflow_statuses', ['workflow_status_id'], ['id'])
    
    # Insert workflow statuses data
    workflow_statuses_table = sa.table('workflow_statuses',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('name_native', sa.String),
        sa.column('description', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime)
    )
    
    op.bulk_insert(workflow_statuses_table, [
        {
            'id': 1,
            'name': 'Draft',
            'name_native': 'Черновик',
            'description': 'Document is in draft status',
            'is_active': True
        },
        {
            'id': 2,
            'name': 'In Review',
            'name_native': 'На рассмотрении',
            'description': 'Document is under review',
            'is_active': True
        },
        {
            'id': 3,
            'name': 'Approved',
            'name_native': 'Утвержден',
            'description': 'Document has been approved',
            'is_active': True
        },
        {
            'id': 4,
            'name': 'Rejected',
            'name_native': 'Отклонен',
            'description': 'Document has been rejected',
            'is_active': True
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_revisions', type_='foreignkey')
    op.drop_column('document_revisions', 'workflow_status_id')
    op.drop_index(op.f('ix_workflow_statuses_id'), table_name='workflow_statuses')
    op.drop_table('workflow_statuses')
    # ### end Alembic commands ###
