"""remove_unique_constraint_from_document_types_code

Revision ID: 114c11a7c7c9
Revises: 309fab3efd10
Create Date: 2025-10-02 10:41:13.464943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114c11a7c7c9'
down_revision: Union[str, None] = '309fab3efd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    # ### end Alembic commands ###
