"""Add unique constraint to project_members

Revision ID: 143f0286f64b
Revises: 201a56fb677f
Create Date: 2025-10-11 13:38:29.080545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143f0286f64b'
down_revision: Union[str, None] = '201a56fb677f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_revisions', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    
    # Добавляем уникальное ограничение для project_members
    op.create_unique_constraint(
        'uq_project_members_project_user',
        'project_members',
        ['project_id', 'user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_revisions', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    
    # Удаляем уникальное ограничение для project_members
    op.drop_constraint(
        'uq_project_members_project_user',
        'project_members',
        type_='unique'
    )
    # ### end Alembic commands ###
