"""Initial migration

Revision ID: 1769fbfe310d
Revises: 
Create Date: 2025-10-15 16:09:52.582871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1769fbfe310d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transmittals', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transmittals', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_transmittals_direction', table_name='transmittals')
    op.drop_index('ix_transmittals_transmittal_date', table_name='transmittals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transmittals_transmittal_date', 'transmittals', ['transmittal_date'], unique=False)
    op.create_index('ix_transmittals_direction', 'transmittals', ['direction'], unique=False)
    op.alter_column('transmittals', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('transmittals', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
