"""fix_roles_structure_use_existing_user_roles

Revision ID: 178bf011730b
Revises: a0ba9fd0ee14
Create Date: 2025-10-05 19:04:13.602784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '178bf011730b'
down_revision: Union[str, None] = 'a0ba9fd0ee14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_roles_id', table_name='system_roles')
    op.drop_table('system_roles')
    op.add_column('user_roles', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('user_roles', sa.Column('name_en', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user_roles', ['code'])
    op.add_column('users', sa.Column('user_role_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_system_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user_roles', ['user_role_id'], ['id'])
    op.drop_column('users', 'system_role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('system_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_system_role_id_fkey', 'users', 'system_roles', ['system_role_id'], ['id'])
    op.drop_column('users', 'user_role_id')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_column('user_roles', 'name_en')
    op.drop_column('user_roles', 'code')
    op.create_table('system_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_roles_pkey'),
    sa.UniqueConstraint('code', name='system_roles_code_key')
    )
    op.create_index('ix_system_roles_id', 'system_roles', ['id'], unique=False)
    # ### end Alembic commands ###
