"""add_workflow_preset_id_to_projects

Revision ID: 19fd091fc3d7
Revises: 4abf1a7d7876
Create Date: 2025-10-05 23:07:02.905816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fd091fc3d7'
down_revision: Union[str, None] = '4abf1a7d7876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workflow_preset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'workflow_presets', ['workflow_preset_id'], ['id'])
    op.alter_column('user_roles', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('workflow_preset_rules', 'operator',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equals'::character varying"))
    op.alter_column('workflow_preset_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_preset_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('workflow_preset_rules', 'operator',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equals'::character varying"))
    op.alter_column('user_roles', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'workflow_preset_id')
    # ### end Alembic commands ###
