"""refactor_remove_project_disciplines_rename_table

Revision ID: 22222a2d91bb
Revises: bf5a9f8f47fd
Create Date: 2025-10-05 01:02:21.781880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22222a2d91bb'
down_revision: Union[str, None] = 'bf5a9f8f47fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Удаляем избыточную таблицу project_disciplines
    op.drop_index('ix_project_disciplines_id', table_name='project_disciplines')
    op.drop_table('project_disciplines')
    
    # 2. Переименовываем project_document_types в project_discipline_document_types
    op.rename_table('project_document_types', 'project_discipline_document_types')
    
    # 3. Переименовываем индексы (только существующие)
    op.execute("ALTER INDEX ix_project_document_types_id RENAME TO ix_project_discipline_document_types_id")
    
    # 4. Переименовываем внешние ключи
    op.execute("ALTER TABLE project_discipline_document_types RENAME CONSTRAINT project_document_types_project_id_fkey TO project_discipline_document_types_project_id_fkey")
    op.execute("ALTER TABLE project_discipline_document_types RENAME CONSTRAINT project_document_types_discipline_id_fkey TO project_discipline_document_types_discipline_id_fkey")
    op.execute("ALTER TABLE project_discipline_document_types RENAME CONSTRAINT project_document_types_document_type_id_fkey TO project_discipline_document_types_document_type_id_fkey")
    op.execute("ALTER TABLE project_discipline_document_types RENAME CONSTRAINT project_document_types_pkey TO project_discipline_document_types_pkey")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Переименовываем обратно project_discipline_document_types в project_document_types
    op.rename_table('project_discipline_document_types', 'project_document_types')
    
    # 2. Переименовываем индексы обратно
    op.execute("ALTER INDEX ix_project_discipline_document_types_id RENAME TO ix_project_document_types_id")
    
    # 3. Переименовываем внешние ключи обратно
    op.execute("ALTER TABLE project_document_types RENAME CONSTRAINT project_discipline_document_types_project_id_fkey TO project_document_types_project_id_fkey")
    op.execute("ALTER TABLE project_document_types RENAME CONSTRAINT project_discipline_document_types_discipline_id_fkey TO project_document_types_discipline_id_fkey")
    op.execute("ALTER TABLE project_document_types RENAME CONSTRAINT project_discipline_document_types_document_type_id_fkey TO project_document_types_document_type_id_fkey")
    op.execute("ALTER TABLE project_document_types RENAME CONSTRAINT project_discipline_document_types_pkey TO project_document_types_pkey")
    
    # 4. Восстанавливаем таблицу project_disciplines
    op.create_table('project_disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_disciplines_id', 'project_disciplines', ['id'], unique=False)
    
    # ### end Alembic commands ###
