"""Change transmittal recipient_id to reference companies

Revision ID: 23435a5de394
Revises: be7802cab10d
Create Date: 2025-10-13 11:05:18.991987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23435a5de394'
down_revision: Union[str, None] = 'be7802cab10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transmittal_revisions', 'revision_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_transmittal_items_id', table_name='transmittal_revisions')
    op.create_index(op.f('ix_transmittal_revisions_id'), 'transmittal_revisions', ['id'], unique=False)
    op.drop_constraint('transmittals_recipient_id_fkey', 'transmittals', type_='foreignkey')
    op.create_foreign_key(None, 'transmittals', 'companies', ['recipient_id'], ['id'])
    op.alter_column('workflow_preset_sequences', 'requires_transmittal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_preset_sequences', 'requires_transmittal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'transmittals', type_='foreignkey')
    op.create_foreign_key('transmittals_recipient_id_fkey', 'transmittals', 'users', ['recipient_id'], ['id'])
    op.drop_index(op.f('ix_transmittal_revisions_id'), table_name='transmittal_revisions')
    op.create_index('ix_transmittal_items_id', 'transmittal_revisions', ['id'], unique=False)
    op.alter_column('transmittal_revisions', 'revision_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
