"""add_document_metadata_fields

Revision ID: 237f241709ac
Revises: 51f7666ce329
Create Date: 2025-09-26 18:41:57.610733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237f241709ac'
down_revision: Union[str, None] = '51f7666ce329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_code', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('documents', sa.Column('author', sa.String(length=200), nullable=True))
    op.add_column('documents', sa.Column('creation_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('revision', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('sheet_number', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('total_sheets', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('scale', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('format', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('confidentiality', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'confidentiality')
    op.drop_column('documents', 'format')
    op.drop_column('documents', 'scale')
    op.drop_column('documents', 'total_sheets')
    op.drop_column('documents', 'sheet_number')
    op.drop_column('documents', 'revision')
    op.drop_column('documents', 'creation_date')
    op.drop_column('documents', 'author')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'document_code')
    # ### end Alembic commands ###
