"""rename_revision_to_number_in_document_revisions

Revision ID: 2aae2c4a3872
Revises: 114c11a7c7c9
Create Date: 2025-10-02 11:28:19.799388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aae2c4a3872'
down_revision: Union[str, None] = '114c11a7c7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем новое поле как nullable
    op.add_column('document_revisions', sa.Column('number', sa.String(length=8), nullable=True))
    
    # Копируем данные из старого поля в новое (обрезаем до 8 символов)
    op.execute("UPDATE document_revisions SET number = LEFT(revision, 8)")
    
    # Делаем поле NOT NULL
    op.alter_column('document_revisions', 'number', nullable=False)
    
    # Удаляем старое поле
    op.drop_column('document_revisions', 'revision')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_revisions', sa.Column('revision', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('document_revisions', 'number')
    # ### end Alembic commands ###
