"""remove_role_from_companies

Revision ID: 2bbda803ac55
Revises: 6da6870d7408
Create Date: 2025-10-03 14:41:12.452860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbda803ac55'
down_revision: Union[str, None] = '6da6870d7408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
