"""remove_file_fields_from_document_revisions

Revision ID: 31a071e20399
Revises: 7e993f56e902
Create Date: 2025-01-27 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a071e20399'
down_revision: Union[str, None] = '7e993f56e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем рудиментарные поля из document_revisions
    # Файлы теперь хранятся в отдельной таблице files
    op.drop_column('document_revisions', 'file_type')
    op.drop_column('document_revisions', 'file_size')
    op.drop_column('document_revisions', 'file_name')
    op.drop_column('document_revisions', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # При откате миграции восстанавливаем поля
    op.add_column('document_revisions', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('document_revisions', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('document_revisions', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('document_revisions', sa.Column('file_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

