"""Remove file fields from documents table

Revision ID: 34db57af916b
Revises: 0405e8b273fa
Create Date: 2025-09-30 15:24:05.366610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34db57af916b'
down_revision: Union[str, None] = '0405e8b273fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_disciplines_discipline_id', table_name='project_disciplines')
    op.drop_index('ix_project_disciplines_id', table_name='project_disciplines')
    op.drop_index('ix_project_disciplines_project_id', table_name='project_disciplines')
    op.drop_table('project_disciplines')
    op.drop_index('ix_project_document_types_discipline_id', table_name='project_document_types')
    op.drop_index('ix_project_document_types_document_type_id', table_name='project_document_types')
    op.drop_index('ix_project_document_types_id', table_name='project_document_types')
    op.drop_index('ix_project_document_types_project_id', table_name='project_document_types')
    op.drop_table('project_document_types')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_name')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'])
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table('project_document_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discipline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name='project_document_types_discipline_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name='project_document_types_document_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_document_types_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_document_types_pkey')
    )
    op.create_index('ix_project_document_types_project_id', 'project_document_types', ['project_id'], unique=False)
    op.create_index('ix_project_document_types_id', 'project_document_types', ['id'], unique=False)
    op.create_index('ix_project_document_types_document_type_id', 'project_document_types', ['document_type_id'], unique=False)
    op.create_index('ix_project_document_types_discipline_id', 'project_document_types', ['discipline_id'], unique=False)
    op.create_table('project_disciplines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discipline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name='project_disciplines_discipline_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_disciplines_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_disciplines_pkey')
    )
    op.create_index('ix_project_disciplines_project_id', 'project_disciplines', ['project_id'], unique=False)
    op.create_index('ix_project_disciplines_id', 'project_disciplines', ['id'], unique=False)
    op.create_index('ix_project_disciplines_discipline_id', 'project_disciplines', ['discipline_id'], unique=False)
    # ### end Alembic commands ###
