"""add_created_by_to_transmittals_manual

Revision ID: 3c173db680b8
Revises: b0b8e4094a82
Create Date: 2025-10-13 22:47:07.024738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c173db680b8'
down_revision: Union[str, None] = 'b0b8e4094a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transmittals', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_transmittals_created_by', 'transmittals', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transmittals_created_by', 'transmittals', type_='foreignkey')
    op.drop_column('transmittals', 'created_by')
    # ### end Alembic commands ###
