"""add_cancelled_status_to_project_enum

Revision ID: 3fd5239a3f87
Revises: 631bf5f0fe74
Create Date: 2025-10-03 15:54:25.872388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd5239a3f87'
down_revision: Union[str, None] = '631bf5f0fe74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новое значение в enum
    op.execute("ALTER TYPE projectstatusenum ADD VALUE 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # В PostgreSQL нельзя удалить значение из enum, поэтому оставляем пустым
    # Если нужно откатить, потребуется пересоздать enum
    pass
    # ### end Alembic commands ###
