"""refactor_project_participants_add_contacts_and_roles

Revision ID: 54ceae9b4a31
Revises: c2db4840b81d
Create Date: 2025-10-03 14:24:59.134463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ceae9b4a31'
down_revision: Union[str, None] = 'c2db4840b81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_company_roles_id'), 'company_roles', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.add_column('project_participants', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('project_participants', sa.Column('company_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_participants', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'project_participants', 'company_roles', ['company_role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('project_participants', 'role')
    op.drop_column('project_participants', 'phone')
    op.drop_column('project_participants', 'email')
    op.drop_column('project_participants', 'contact_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_participants', sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('project_participants', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('project_participants', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('project_participants', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_participants', type_='foreignkey')
    op.drop_constraint(None, 'project_participants', type_='foreignkey')
    op.drop_column('project_participants', 'company_role_id')
    op.drop_column('project_participants', 'contact_id')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_roles_id'), table_name='company_roles')
    op.drop_table('company_roles')
    # ### end Alembic commands ###
