"""add_project_status_enum

Revision ID: 631bf5f0fe74
Revises: 2bbda803ac55
Create Date: 2025-10-03 15:52:15.935058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631bf5f0fe74'
down_revision: Union[str, None] = '2bbda803ac55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum тип
    project_status_enum = sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', name='projectstatusenum')
    project_status_enum.create(op.get_bind())
    
    # Убираем дефолтное значение
    op.alter_column('projects', 'status', server_default=None)
    
    # Обновляем существующие данные
    op.execute("UPDATE projects SET status = 'ACTIVE' WHERE status = 'active'")
    op.execute("UPDATE projects SET status = 'PLANNING' WHERE status = 'planning'")
    op.execute("UPDATE projects SET status = 'COMPLETED' WHERE status = 'completed'")
    
    # Изменяем тип колонки
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=project_status_enum,
               existing_nullable=True,
               postgresql_using='status::projectstatusenum')
    
    # Устанавливаем новое дефолтное значение
    op.alter_column('projects', 'status', server_default='ACTIVE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем к VARCHAR
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', name='projectstatusenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using='status::text')
    
    # Обновляем данные обратно
    op.execute("UPDATE projects SET status = 'active' WHERE status = 'ACTIVE'")
    op.execute("UPDATE projects SET status = 'planning' WHERE status = 'PLANNING'")
    op.execute("UPDATE projects SET status = 'completed' WHERE status = 'COMPLETED'")
    
    # Удаляем enum тип
    op.execute("DROP TYPE projectstatusenum")
    # ### end Alembic commands ###
