"""add_en_fields_to_disciplines_and_document_types

Revision ID: 65c28c8e3fda
Revises: be16b5ba7b44
Create Date: 2025-09-26 15:35:58.470437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c28c8e3fda'
down_revision: Union[str, None] = 'be16b5ba7b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('disciplines', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('document_types', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('document_types', sa.Column('description_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'description_en')
    op.drop_column('document_types', 'name_en')
    op.drop_column('disciplines', 'description_en')
    op.drop_column('disciplines', 'name_en')
    # ### end Alembic commands ###
