"""make_ccs_status_nullable

Revision ID: 67e05a293835
Revises: a9334f2c129a
Create Date: 2026-01-20 16:25:47.091813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67e05a293835'
down_revision: Union[str, None] = 'a9334f2c129a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transmittal_revisions', 'ccs_status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='ccsstatus'),
               nullable=True,
               existing_server_default=sa.text("'OPEN'::ccsstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transmittal_revisions', 'ccs_status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='ccsstatus'),
               nullable=False,
               existing_server_default=sa.text("'OPEN'::ccsstatus"))
    # ### end Alembic commands ###
