"""remove_code_from_companies

Revision ID: 6da6870d7408
Revises: 54ceae9b4a31
Create Date: 2025-10-03 14:31:33.386042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da6870d7408'
down_revision: Union[str, None] = '54ceae9b4a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_code_key', 'companies', type_='unique')
    op.drop_column('companies', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_unique_constraint('companies_code_key', 'companies', ['code'])
    # ### end Alembic commands ###
