"""Add project workflow sequence and rules tables

Revision ID: 720050b338ee
Revises: dbbe94d0d582
Create Date: 2025-10-03 08:59:37.624163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720050b338ee'
down_revision: Union[str, None] = 'dbbe94d0d582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_workflow_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('current_revision_description_id', sa.Integer(), nullable=True),
    sa.Column('current_revision_step_id', sa.Integer(), nullable=True),
    sa.Column('review_code_id', sa.Integer(), nullable=True),
    sa.Column('next_revision_description_id', sa.Integer(), nullable=True),
    sa.Column('next_revision_step_id', sa.Integer(), nullable=True),
    sa.Column('action_on_fail', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_code_id'], ['review_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_workflow_rules_id'), 'project_workflow_rules', ['id'], unique=False)
    op.create_table('project_workflow_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('revision_description_id', sa.Integer(), nullable=True),
    sa.Column('revision_step_id', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_workflow_sequences_id'), 'project_workflow_sequences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_workflow_sequences_id'), table_name='project_workflow_sequences')
    op.drop_table('project_workflow_sequences')
    op.drop_index(op.f('ix_project_workflow_rules_id'), table_name='project_workflow_rules')
    op.drop_table('project_workflow_rules')
    # ### end Alembic commands ###
