"""Add unique constraint to project_participants

Revision ID: 76b73595bed4
Revises: 143f0286f64b
Create Date: 2025-10-11 13:40:28.856203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b73595bed4'
down_revision: Union[str, None] = '07e1c7cbf51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем уникальное ограничение для project_participants
    op.create_unique_constraint(
        'uq_project_participants_project_company',
        'project_participants',
        ['project_id', 'company_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем уникальное ограничение для project_participants
    op.drop_constraint(
        'uq_project_participants_project_company',
        'project_participants',
        type_='unique'
    )
    # ### end Alembic commands ###
