"""Add language_id field to documents table

Revision ID: 791c5188f863
Revises: 8edd182fb787
Create Date: 2025-09-30 18:42:07.760943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791c5188f863'
down_revision: Union[str, None] = '8edd182fb787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'language_id')
    # ### end Alembic commands ###
