"""create_files_table_for_document_revisions

Revision ID: 7e993f56e902
Revises: ff4b3d7addd3
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e993f56e902'
down_revision: Union[str, None] = 'ff4b3d7addd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу files
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    
    # Мигрируем существующие данные из document_revisions в files
    connection = op.get_bind()
    
    # Переносим данные из document_revisions в files, если они есть
    # Проверяем, есть ли данные для миграции
    result = connection.execute(sa.text("""
        SELECT COUNT(*) 
        FROM document_revisions 
        WHERE file_path IS NOT NULL 
        AND file_name IS NOT NULL
        AND is_deleted = 0
    """))
    count = result.scalar()
    
    if count > 0:
        # Переносим данные из document_revisions в files
        # Используем id как revision_id, так как мы вставляем в таблицу files записи для каждой ревизии
        connection.execute(sa.text("""
            INSERT INTO files (revision_id, file_path, file_name, file_size, file_type, uploaded_by, created_at, is_deleted)
            SELECT 
                dr.id as revision_id,
                dr.file_path,
                dr.file_name,
                dr.file_size,
                dr.file_type,
                dr.uploaded_by,
                dr.created_at,
                dr.is_deleted
            FROM document_revisions dr
            WHERE dr.file_path IS NOT NULL 
            AND dr.file_name IS NOT NULL
            AND dr.is_deleted = 0
        """))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # При откате миграции просто удаляем таблицу files
    # Данные из document_revisions остаются без изменений
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###

