"""Change is_deleted to Integer and populate data for new fields

Revision ID: 89aa53c8e070
Revises: 791c5188f863
Create Date: 2025-09-30 18:54:55.326598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aa53c8e070'
down_revision: Union[str, None] = '791c5188f863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Добавляем временную колонку для нового типа
    op.add_column('documents', sa.Column('is_deleted_new', sa.Integer(), nullable=True))
    
    # Копируем данные из старой колонки в новую
    connection.execute(
        sa.text("""
            UPDATE documents 
            SET is_deleted_new = CASE 
                WHEN is_deleted IS NULL THEN 0
                WHEN is_deleted = false THEN 0
                WHEN is_deleted = true THEN 1
                ELSE 0
            END
        """)
    )
    
    # Удаляем старую колонку
    op.drop_column('documents', 'is_deleted')
    
    # Переименовываем новую колонку
    op.alter_column('documents', 'is_deleted_new', new_column_name='is_deleted')
    
    # Заполняем number (генерируем номера документов)
    connection.execute(
        sa.text("""
            UPDATE documents 
            SET number = 'DOC-' || LPAD(id::text, 6, '0')
            WHERE number IS NULL
        """)
    )
    
    # Заполняем drs (генерируем DRS коды)
    connection.execute(
        sa.text("""
            UPDATE documents 
            SET drs = 'DRS-' || LPAD(id::text, 8, '0')
            WHERE drs IS NULL
        """)
    )
    
    # Заполняем language_id (устанавливаем русский язык по умолчанию)
    # Сначала убедимся, что есть русский язык в таблице languages
    connection.execute(
        sa.text("""
            INSERT INTO languages (name, name_native, code, is_active, created_at)
            SELECT 'Русский', 'Русский', 'ru', true, NOW()
            WHERE NOT EXISTS (SELECT 1 FROM languages WHERE code = 'ru')
        """)
    )
    
    # Обновляем language_id для документов без языка
    connection.execute(
        sa.text("""
            UPDATE documents 
            SET language_id = (SELECT id FROM languages WHERE code = 'ru' LIMIT 1)
            WHERE language_id IS NULL
        """)
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
