"""Add number, is_deleted, drs fields to documents table

Revision ID: 8edd182fb787
Revises: 073bc109bb7a
Create Date: 2025-09-30 18:07:22.280953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edd182fb787'
down_revision: Union[str, None] = '073bc109bb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('number', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('drs', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'drs')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'number')
    # ### end Alembic commands ###
