"""Add budget, client, manager_id to projects table

Revision ID: 9069736d1a75
Revises: 745f6a4833ff
Create Date: 2025-09-25 14:32:28.382527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9069736d1a75'
down_revision: Union[str, None] = '745f6a4833ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('projects', sa.Column('client', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'manager_id')
    op.drop_column('projects', 'client')
    op.drop_column('projects', 'budget')
    # ### end Alembic commands ###
