"""add_transmittal_export_settings_table

Revision ID: 9428011d1f53
Revises: dc6a6719d0e1
Create Date: 2025-10-16 15:04:56.442162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9428011d1f53'
down_revision: Union[str, None] = 'dc6a6719d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transmittal_export_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transmittal_number_label', sa.String(length=100), nullable=True),
    sa.Column('document_number_label', sa.String(length=100), nullable=True),
    sa.Column('status_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmittal_export_settings_id'), 'transmittal_export_settings', ['id'], unique=False)
    op.alter_column('transmittals', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transmittals', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_transmittals_direction', table_name='transmittals')
    op.drop_index('ix_transmittals_transmittal_date', table_name='transmittals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transmittals_transmittal_date', 'transmittals', ['transmittal_date'], unique=False)
    op.create_index('ix_transmittals_direction', 'transmittals', ['direction'], unique=False)
    op.alter_column('transmittals', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('transmittals', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_transmittal_export_settings_id'), table_name='transmittal_export_settings')
    op.drop_table('transmittal_export_settings')
    # ### end Alembic commands ###
