"""Add document_workflow_history table

Revision ID: 9b35df6e53f2
Revises: a398223f0ae6
Create Date: 2025-10-19 21:21:43.063337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b35df6e53f2'
down_revision: Union[str, None] = 'a398223f0ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
