"""Remove cancelled_by and cancelled_at from document_revisions

Revision ID: a07d98eda1ef
Revises: cb62149c4682
Create Date: 2025-10-11 19:20:07.285925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a07d98eda1ef'
down_revision: Union[str, None] = 'cb62149c4682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_revisions_cancelled_by_fkey', 'document_revisions', type_='foreignkey')
    op.drop_column('document_revisions', 'cancelled_at')
    op.drop_column('document_revisions', 'cancelled_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_revisions', sa.Column('cancelled_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_revisions', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('document_revisions_cancelled_by_fkey', 'document_revisions', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###
