"""add_system_and_project_roles

Revision ID: a0ba9fd0ee14
Revises: f7f7dcedc6ec
Create Date: 2025-10-05 18:59:14.497874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ba9fd0ee14'
down_revision: Union[str, None] = 'f7f7dcedc6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_project_roles_id'), 'project_roles', ['id'], unique=False)
    op.create_table('system_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_system_roles_id'), 'system_roles', ['id'], unique=False)
    op.add_column('project_members', sa.Column('project_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_members', 'project_roles', ['project_role_id'], ['id'])
    op.add_column('users', sa.Column('system_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'system_roles', ['system_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'system_role_id')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'project_role_id')
    op.drop_index(op.f('ix_system_roles_id'), table_name='system_roles')
    op.drop_table('system_roles')
    op.drop_index(op.f('ix_project_roles_id'), table_name='project_roles')
    op.drop_table('project_roles')
    # ### end Alembic commands ###
