"""remove_client_field_from_projects

Revision ID: abc4f1ea0e5f
Revises: 3fd5239a3f87
Create Date: 2025-10-03 15:56:28.763610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc4f1ea0e5f'
down_revision: Union[str, None] = '3fd5239a3f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
