"""Update notifications table

Revision ID: b026bfd1a257
Revises: 01bafa292c77
Create Date: 2025-09-29 18:52:49.394760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b026bfd1a257'
down_revision: Union[str, None] = '01bafa292c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'document_id')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'priority')
    # ### end Alembic commands ###
