"""add_created_by_to_transmittals

Revision ID: b0b8e4094a82
Revises: 4df831c434a9
Create Date: 2025-10-13 22:42:39.896186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b8e4094a82'
down_revision: Union[str, None] = '4df831c434a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_revisions_document_created', table_name='document_revisions')
    op.drop_index('idx_document_revisions_status_deleted', table_name='document_revisions')
    op.drop_index('idx_documents_discipline_type', table_name='documents')
    op.drop_index('idx_documents_project_deleted', table_name='documents')
    op.drop_index('idx_project_discipline_doc_types_lookup', table_name='project_discipline_document_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_discipline_doc_types_lookup', 'project_discipline_document_types', ['project_id', 'discipline_id', 'document_type_id'], unique=False)
    op.create_index('idx_documents_project_deleted', 'documents', ['project_id', 'is_deleted'], unique=False)
    op.create_index('idx_documents_discipline_type', 'documents', ['discipline_id', 'document_type_id'], unique=False)
    op.create_index('idx_document_revisions_status_deleted', 'document_revisions', ['revision_status_id', 'is_deleted'], unique=False)
    op.create_index('idx_document_revisions_document_created', 'document_revisions', ['document_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
