"""fix_foreign_keys_in_discipline_tables

Revision ID: be16b5ba7b44
Revises: ebfff3c40658
Create Date: 2025-09-26 10:56:11.246756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be16b5ba7b44'
down_revision: Union[str, None] = 'ebfff3c40658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_disciplines', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_disciplines', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_document_types', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_document_types', 'document_types', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_document_types', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_document_types', type_='foreignkey')
    op.drop_constraint(None, 'project_document_types', type_='foreignkey')
    op.drop_constraint(None, 'project_document_types', type_='foreignkey')
    op.drop_constraint(None, 'project_disciplines', type_='foreignkey')
    op.drop_constraint(None, 'project_disciplines', type_='foreignkey')
    # ### end Alembic commands ###
