"""remove_client_field_from_projects_v2

Revision ID: bf5a9f8f47fd
Revises: abc4f1ea0e5f
Create Date: 2025-10-03 15:57:03.707996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5a9f8f47fd'
down_revision: Union[str, None] = 'abc4f1ea0e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
