"""Add cancelled_by and cancelled_at to document_revisions

Revision ID: cb62149c4682
Revises: 76b73595bed4
Create Date: 2025-10-11 19:13:12.483348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb62149c4682'
down_revision: Union[str, None] = '76b73595bed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_revisions', sa.Column('cancelled_by', sa.Integer(), nullable=True))
    op.add_column('document_revisions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'document_revisions', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_revisions', type_='foreignkey')
    op.drop_column('document_revisions', 'cancelled_at')
    op.drop_column('document_revisions', 'cancelled_by')
    # ### end Alembic commands ###
