"""update_transmittal_import_settings_structure

Revision ID: da1c18593cc6
Revises: 9428011d1f53
Create Date: 2025-10-16 15:26:53.627606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da1c18593cc6'
down_revision: Union[str, None] = '9428011d1f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transmittal_import_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('settings_key', sa.String(length=100), nullable=False),
    sa.Column('settings_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmittal_import_settings_id'), 'transmittal_import_settings', ['id'], unique=False)
    op.drop_index('ix_transmittal_export_settings_id', table_name='transmittal_export_settings')
    op.drop_table('transmittal_export_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transmittal_export_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transmittal_number_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_number_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='transmittal_export_settings_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='transmittal_export_settings_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transmittal_export_settings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transmittal_export_settings_pkey')
    )
    op.create_index('ix_transmittal_export_settings_id', 'transmittal_export_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_transmittal_import_settings_id'), table_name='transmittal_import_settings')
    op.drop_table('transmittal_import_settings')
    # ### end Alembic commands ###
