"""Add is_deleted field to projects table

Revision ID: dbbe94d0d582
Revises: 75026ad568b0
Create Date: 2025-10-02 18:48:02.002923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbe94d0d582'
down_revision: Union[str, None] = '75026ad568b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable с default значением
    op.add_column('projects', sa.Column('is_deleted', sa.Integer(), nullable=True, server_default='0'))
    # Обновляем все существующие записи
    op.execute("UPDATE projects SET is_deleted = 0 WHERE is_deleted IS NULL")
    # Делаем колонку NOT NULL
    op.alter_column('projects', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_deleted')
    # ### end Alembic commands ###
