"""Add workflow presets tables

Revision ID: e44396479ea3
Revises: 720050b338ee
Create Date: 2025-10-03 10:44:20.998516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44396479ea3'
down_revision: Union[str, None] = '720050b338ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_presets_id'), 'workflow_presets', ['id'], unique=False)
    op.create_table('workflow_preset_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('current_revision_description_id', sa.Integer(), nullable=True),
    sa.Column('current_revision_step_id', sa.Integer(), nullable=True),
    sa.Column('review_code_id', sa.Integer(), nullable=True),
    sa.Column('next_revision_description_id', sa.Integer(), nullable=True),
    sa.Column('next_revision_step_id', sa.Integer(), nullable=True),
    sa.Column('action_on_fail', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preset_id'], ['workflow_presets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_code_id'], ['review_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_preset_rules_id'), 'workflow_preset_rules', ['id'], unique=False)
    op.create_table('workflow_preset_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('revision_description_id', sa.Integer(), nullable=True),
    sa.Column('revision_step_id', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preset_id'], ['workflow_presets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_description_id'], ['revision_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_step_id'], ['revision_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_preset_sequences_id'), 'workflow_preset_sequences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_preset_sequences_id'), table_name='workflow_preset_sequences')
    op.drop_table('workflow_preset_sequences')
    op.drop_index(op.f('ix_workflow_preset_rules_id'), table_name='workflow_preset_rules')
    op.drop_table('workflow_preset_rules')
    op.drop_index(op.f('ix_workflow_presets_id'), table_name='workflow_presets')
    op.drop_table('workflow_presets')
    # ### end Alembic commands ###
