"""add_disciplines_and_document_types_tables

Revision ID: ebfff3c40658
Revises: c20170ba7cba
Create Date: 2025-09-26 10:55:08.582844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfff3c40658'
down_revision: Union[str, None] = 'c20170ba7cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplines_code'), 'disciplines', ['code'], unique=True)
    op.create_index(op.f('ix_disciplines_id'), 'disciplines', ['id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('project_disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_disciplines_discipline_id'), 'project_disciplines', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_project_disciplines_id'), 'project_disciplines', ['id'], unique=False)
    op.create_index(op.f('ix_project_disciplines_project_id'), 'project_disciplines', ['project_id'], unique=False)
    op.create_table('project_document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_document_types_discipline_id'), 'project_document_types', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_project_document_types_document_type_id'), 'project_document_types', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_project_document_types_id'), 'project_document_types', ['id'], unique=False)
    op.create_index(op.f('ix_project_document_types_project_id'), 'project_document_types', ['project_id'], unique=False)
    op.add_column('documents', sa.Column('discipline_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('document_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'disciplines', ['discipline_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'document_types', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type_id')
    op.drop_column('documents', 'discipline_id')
    op.drop_index(op.f('ix_project_document_types_project_id'), table_name='project_document_types')
    op.drop_index(op.f('ix_project_document_types_id'), table_name='project_document_types')
    op.drop_index(op.f('ix_project_document_types_document_type_id'), table_name='project_document_types')
    op.drop_index(op.f('ix_project_document_types_discipline_id'), table_name='project_document_types')
    op.drop_table('project_document_types')
    op.drop_index(op.f('ix_project_disciplines_project_id'), table_name='project_disciplines')
    op.drop_index(op.f('ix_project_disciplines_id'), table_name='project_disciplines')
    op.drop_index(op.f('ix_project_disciplines_discipline_id'), table_name='project_disciplines')
    op.drop_table('project_disciplines')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_disciplines_id'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_code'), table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
