"""add_area_model

Revision ID: efe95db06479
Revises: b24c1c26cf06
Create Date: 2026-01-01 13:25:19.514456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe95db06479'
down_revision: Union[str, None] = 'b24c1c26cf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('areas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('files', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_support_messages_created_at', table_name='support_messages')
    op.drop_index('ix_support_messages_ticket_id', table_name='support_messages')
    op.drop_index('ix_support_ticket_files_message_id', table_name='support_ticket_files')
    op.drop_index('ix_support_ticket_files_ticket_id', table_name='support_ticket_files')
    
    # Создаем enum тип для статуса тикета
    ticketstatus_enum = sa.Enum('new', 'in_progress', 'resolved', 'closed', name='ticketstatus')
    ticketstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Сначала нормализуем существующие значения в базе данных (приводим к нижнему регистру)
    # и преобразуем возможные варианты написания
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE support_tickets 
        SET status = LOWER(status)
        WHERE status != LOWER(status)
    """))
    
    # Преобразуем возможные варианты значений
    connection.execute(sa.text("""
        UPDATE support_tickets 
        SET status = CASE 
            WHEN UPPER(status) = 'NEW' THEN 'new'
            WHEN UPPER(status) = 'IN_PROGRESS' OR UPPER(status) = 'IN PROGRESS' THEN 'in_progress'
            WHEN UPPER(status) = 'RESOLVED' THEN 'resolved'
            WHEN UPPER(status) = 'CLOSED' THEN 'closed'
            ELSE LOWER(status)
        END
    """))
    
    # Сначала удаляем значение по умолчанию
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    
    # Изменяем тип колонки status на enum с преобразованием значений
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=ticketstatus_enum,
               postgresql_using='LOWER(status)::ticketstatus',
               existing_nullable=False)
    
    # Устанавливаем новое значение по умолчанию для enum
    op.alter_column('support_tickets', 'status',
               existing_type=ticketstatus_enum,
               server_default=sa.text("'new'::ticketstatus"),
               existing_nullable=False)
    
    op.drop_index('ix_support_tickets_last_message_at', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_user_id', table_name='support_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_support_tickets_user_id', 'support_tickets', ['user_id'], unique=False)
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_last_message_at', 'support_tickets', ['last_message_at'], unique=False)
    
    # Сначала удаляем значение по умолчанию
    op.alter_column('support_tickets', 'status',
               existing_type=sa.Enum('new', 'in_progress', 'resolved', 'closed', name='ticketstatus'),
               server_default=None,
               existing_nullable=False)
    
    # Возвращаем тип колонки обратно в VARCHAR
    op.alter_column('support_tickets', 'status',
               existing_type=sa.Enum('new', 'in_progress', 'resolved', 'closed', name='ticketstatus'),
               type_=sa.VARCHAR(length=20),
               postgresql_using='status::text',
               existing_nullable=False)
    
    # Восстанавливаем значение по умолчанию для VARCHAR
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'new'::character varying"),
               existing_nullable=False)
    
    # Удаляем enum тип
    ticketstatus_enum = sa.Enum(name='ticketstatus')
    ticketstatus_enum.drop(op.get_bind(), checkfirst=True)
    
    op.create_index('ix_support_ticket_files_ticket_id', 'support_ticket_files', ['ticket_id'], unique=False)
    op.create_index('ix_support_ticket_files_message_id', 'support_ticket_files', ['message_id'], unique=False)
    op.create_index('ix_support_messages_ticket_id', 'support_messages', ['ticket_id'], unique=False)
    op.create_index('ix_support_messages_created_at', 'support_messages', ['created_at'], unique=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('areas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    # ### end Alembic commands ###
