"""add_operators_to_workflow_preset_rules

Revision ID: f366adbaab14
Revises: 9d3a198433f1
Create Date: 2025-10-05 20:38:41.030436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f366adbaab14'
down_revision: Union[str, None] = '9d3a198433f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поле operator для поддержки операторов сравнения
    op.add_column('workflow_preset_rules', 
        sa.Column('operator', sa.String(20), nullable=False, server_default='equals'))
    
    # Добавляем поле review_code_list для списковых операторов
    op.add_column('workflow_preset_rules', 
        sa.Column('review_code_list', sa.Text(), nullable=True))
    
    # Добавляем поле priority для порядка обработки правил
    op.add_column('workflow_preset_rules', 
        sa.Column('priority', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем добавленные поля
    op.drop_column('workflow_preset_rules', 'priority')
    op.drop_column('workflow_preset_rules', 'review_code_list')
    op.drop_column('workflow_preset_rules', 'operator')
    # ### end Alembic commands ###
