"""add_drs_to_project_discipline_document_types_remove_from_documents

Revision ID: f7f7dcedc6ec
Revises: 22222a2d91bb
Create Date: 2025-10-05 01:22:51.950535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f7dcedc6ec'
down_revision: Union[str, None] = '22222a2d91bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Добавляем поле drs в project_discipline_document_types
    op.add_column('project_discipline_document_types', 
                  sa.Column('drs', sa.String(length=50), nullable=True))
    
    # 2. Копируем данные drs из documents в project_discipline_document_types
    # Сначала получаем все связи project-discipline-document_type из documents
    op.execute("""
        INSERT INTO project_discipline_document_types (project_id, discipline_id, document_type_id, drs, created_at)
        SELECT DISTINCT 
            d.project_id,
            d.discipline_id,
            d.document_type_id,
            d.drs,
            NOW()
        FROM documents d
        WHERE d.discipline_id IS NOT NULL 
        AND d.document_type_id IS NOT NULL
        AND d.drs IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM project_discipline_document_types pddt
            WHERE pddt.project_id = d.project_id
            AND pddt.discipline_id = d.discipline_id
            AND pddt.document_type_id = d.document_type_id
        )
    """)
    
    # 3. Удаляем поле drs из documents
    op.drop_column('documents', 'drs')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Добавляем поле drs обратно в documents
    op.add_column('documents', 
                  sa.Column('drs', sa.String(length=50), nullable=True))
    
    # 2. Копируем данные drs обратно из project_discipline_document_types в documents
    op.execute("""
        UPDATE documents d
        SET drs = pddt.drs
        FROM project_discipline_document_types pddt
        WHERE d.project_id = pddt.project_id
        AND d.discipline_id = pddt.discipline_id
        AND d.document_type_id = pddt.document_type_id
        AND pddt.drs IS NOT NULL
    """)
    
    # 3. Удаляем поле drs из project_discipline_document_types
    op.drop_column('project_discipline_document_types', 'drs')
    
    # ### end Alembic commands ###
