"""remove_document_type_id_from_workflow_preset_sequences

Revision ID: ff4b3d7addd3
Revises: 67688e9c66ed
Create Date: 2025-10-20 00:54:46.385562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4b3d7addd3'
down_revision: Union[str, None] = '67688e9c66ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_preset_sequences_document_type_id_fkey', 'workflow_preset_sequences', type_='foreignkey')
    op.drop_column('workflow_preset_sequences', 'document_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_preset_sequences', sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('workflow_preset_sequences_document_type_id_fkey', 'workflow_preset_sequences', 'document_types', ['document_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
