"""Initial migration

Revision ID: 46e0f61bcfc0
Revises: 
Create Date: 2024-05-28 22:23:00.910521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e0f61bcfc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_native', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_native', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_id'), 'audit_logs', ['action_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_native', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('company_participating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_participating_company_id'), 'company_participating', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_participating_id'), 'company_participating', ['id'], unique=False)
    op.create_index(op.f('ix_company_participating_project_id'), 'company_participating', ['project_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_native', sa.String(length=256), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_native', sa.String(length=256), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplines_id'), 'disciplines', ['id'], unique=False)
    op.create_table('document_prefixes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_prefixes_id'), 'document_prefixes', ['id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('name_native', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_native', sa.String(length=512), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('revision_status_id', sa.Integer(), nullable=False),
    sa.Column('revision_step_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_discipline_id'), 'documents', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_language_id'), 'documents', ['language_id'], unique=False)
    op.create_index(op.f('ix_documents_number'), 'documents', ['number'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_revision_status_id'), 'documents', ['revision_status_id'], unique=False)
    op.create_index(op.f('ix_documents_revision_step_id'), 'documents', ['revision_step_id'], unique=False)
    op.create_index(op.f('ix_documents_type_id'), 'documents', ['type_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_native', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_native', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('project_discipline_doctype_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_discipline_doctype_reference_discipline_id'), 'project_discipline_doctype_reference', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_project_discipline_doctype_reference_id'), 'project_discipline_doctype_reference', ['id'], unique=False)
    op.create_index(op.f('ix_project_discipline_doctype_reference_project_id'), 'project_discipline_doctype_reference', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_discipline_doctype_reference_type_id'), 'project_discipline_doctype_reference', ['type_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_native', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('revision_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_native', sa.String(length=512), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_statuses_deadline'), 'revision_statuses', ['deadline'], unique=False)
    op.create_index(op.f('ix_revision_statuses_id'), 'revision_statuses', ['id'], unique=False)
    op.create_table('revision_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_native', sa.String(length=512), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_steps_id'), 'revision_steps', ['id'], unique=False)
    op.create_table('transmittals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Boolean(), nullable=True),
    sa.Column('recieved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmittals_document_id'), 'transmittals', ['document_id'], unique=False)
    op.create_index(op.f('ix_transmittals_id'), 'transmittals', ['id'], unique=False)
    op.create_index(op.f('ix_transmittals_number'), 'transmittals', ['number'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_path'), 'uploaded_files', ['path'], unique=False)
    op.create_table('user_project_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_project_access_id'), 'user_project_access', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_project_access_id'), table_name='user_project_access')
    op.drop_table('user_project_access')
    op.drop_index(op.f('ix_uploaded_files_path'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_transmittals_number'), table_name='transmittals')
    op.drop_index(op.f('ix_transmittals_id'), table_name='transmittals')
    op.drop_index(op.f('ix_transmittals_document_id'), table_name='transmittals')
    op.drop_table('transmittals')
    op.drop_index(op.f('ix_revision_steps_id'), table_name='revision_steps')
    op.drop_table('revision_steps')
    op.drop_index(op.f('ix_revision_statuses_id'), table_name='revision_statuses')
    op.drop_index(op.f('ix_revision_statuses_deadline'), table_name='revision_statuses')
    op.drop_table('revision_statuses')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_discipline_doctype_reference_type_id'), table_name='project_discipline_doctype_reference')
    op.drop_index(op.f('ix_project_discipline_doctype_reference_project_id'), table_name='project_discipline_doctype_reference')
    op.drop_index(op.f('ix_project_discipline_doctype_reference_id'), table_name='project_discipline_doctype_reference')
    op.drop_index(op.f('ix_project_discipline_doctype_reference_discipline_id'), table_name='project_discipline_doctype_reference')
    op.drop_table('project_discipline_doctype_reference')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_documents_type_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_revision_step_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_revision_status_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_language_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_discipline_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_document_prefixes_id'), table_name='document_prefixes')
    op.drop_table('document_prefixes')
    op.drop_index(op.f('ix_disciplines_id'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_company_participating_project_id'), table_name='company_participating')
    op.drop_index(op.f('ix_company_participating_id'), table_name='company_participating')
    op.drop_index(op.f('ix_company_participating_company_id'), table_name='company_participating')
    op.drop_table('company_participating')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
